# Generated by Django 5.2.9 on 2025-12-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("OPD", "Outpatient"),
                            ("IPD", "Inpatient Admission"),
                            ("ER", "Emergency"),
                            ("FU", "Follow-Up"),
                            ("TELE", "Teleconsultation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app1.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("diag_id", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis_code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="app1.encounter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="app1.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                ("lab_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=100)),
                ("result_value", models.CharField(max_length=100)),
                ("result_unit", models.CharField(blank=True, max_length=50)),
                ("reference_range", models.CharField(blank=True, max_length=100)),
                ("test_date", models.DateField()),
                (
                    "encounter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app1.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                ("insurance_id", models.AutoField(primary_key=True, serialize=False)),
                ("provider_name", models.CharField(max_length=100)),
                ("policy_number", models.CharField(max_length=50)),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                ("imm_id", models.AutoField(primary_key=True, serialize=False)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("date_given", models.DateField()),
                ("dose_number", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("allergy_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergen", models.CharField(max_length=100)),
                ("reaction", models.CharField(max_length=200)),
                ("severity", models.CharField(max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_list",
                        to="app1.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vital",
            fields=[
                ("vital_id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.FloatField()),
                ("heart_rate", models.IntegerField()),
                ("blood_pressure", models.CharField(max_length=20)),
                ("oxygen_saturation", models.IntegerField()),
                ("recorded_at", models.DateTimeField()),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="app1.encounter",
                    ),
                ),
            ],
        ),
    ]
