# Generated by Django 5.2.6 on 2025-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_add_booking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="health_check_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reminder",
            name="health_check_required",
            field=models.BooleanField(default=False),
        ),
    ]
